"""``suggest_source_definition`` — auto-draft a source YAML from mined samples.

THE KEY DIFFERENTIATING FEATURE. Every other module in this package answers
"what shape is this line?" (:mod:`~ulpf.parse.templates.miner`), "have we seen
it before?" (:mod:`~ulpf.parse.templates.store`), and "what does each variable
position probably mean?" (:mod:`~ulpf.parse.templates.inference`). This module
is where those three answers become the thing an operator actually needs:
**requirement (i) — reduced parser development effort** — a complete,
schema-valid ``configs/sources/*.yaml`` draft, generated without anyone
hand-writing a grok pattern or guessing at OCSF field paths.

STRATEGY
--------
1. Sniff the samples' format (:func:`~ulpf.detect.sniffer.sniff_layered`,
   majority vote across the sample set).
2. **Structured** (``json``/``kv``/``cef``/``leef``) — run the real parse
   engine over every sample, take the union of observed keys, and map
   straight from key name -> value column. High confidence: the parser
   already told us the field boundaries: no guessing about where one value
   ends and the next begins.
3. **Delimited** (``csv``/``tsv``) — split every sample on the delimiter and
   treat each column position like an unstructured wildcard (below);
   generates a ``csv`` engine definition with inferred column names.
4. **Unstructured** — mine the dominant template
   (:class:`~ulpf.parse.templates.miner`, using the same masking config as
   the live pipeline) and run every sample's parameter list through
   :func:`~ulpf.parse.templates.inference.infer_field_types`. Builds a
   **dissect** pattern (``%{field}`` placeholders, the literal template text
   supplies the delimiters) when every gap between placeholders is
   non-empty; falls back to **grok** only when it is not (dissect cannot
   place an unambiguous boundary between two back-to-back placeholders).
5. **Detect rule**: the longest, most distinctive literal substrings common
   to every sample (for delimited formats, a ``field_count`` fallback).
6. **Semantic -> OCSF**: a fixed table (``source_ip`` -> ``src_endpoint.ip``,
   ``port`` -> ``src_endpoint.port``/``dst_endpoint.port`` by proximity to the
   nearest IP, ``action`` -> ``action_id``/``action``/``disposition`` via a
   value map, ...). Anything left over (``unknown``, a third+ IP, an
   unresolved port/byte slot) is never dropped — it still reaches
   ``unmapped: keep_all``.
7. The returned YAML carries a header comment naming the template/source it
   came from, how many samples, and each field's confidence, plus an inline
   ``# REVIEW REQUIRED`` comment on every mapping whose confidence is below
   :data:`REVIEW_THRESHOLD`. It is **always** re-parsed and validated against
   :class:`~ulpf.parse.dsl.schema.SourceDefinition` before being returned —
   an internal bug here must raise :class:`SuggestError`, never hand back
   YAML that would fail to load.

This is a draft, not an oracle: it is meant to turn a blank page into a
95%-there starting point an operator reviews and commits — not to bypass
human review of what an autogenerated parser does with real evidence.
"""

from __future__ import annotations

import csv
import io
import re
from collections import Counter
from dataclasses import dataclass
from typing import Any

import yaml
from drain3 import TemplateMiner as _Drain3Engine
from pydantic import ValidationError as _PydanticValidationError

from ulpf.config.settings import Settings, get_settings
from ulpf.core.errors import ParseError, UlpfError
from ulpf.detect.sniffer import sniff_layered
from ulpf.parse.dsl.schema import load_source_definition
from ulpf.parse.engines.cef_engine import CefEngine
from ulpf.parse.engines.json_engine import JsonEngine
from ulpf.parse.engines.kv_engine import KvEngine
from ulpf.parse.engines.leef_engine import LeefEngine
from ulpf.parse.syslog_envelope import parse_syslog_envelope
from ulpf.parse.templates.inference import FieldGuess, infer_field_types
from ulpf.parse.templates.miner import load_drain3_config
from ulpf.parse.templates.store import TemplateStore

REVIEW_THRESHOLD = 0.7
_MIN_SAMPLES = 3
_MIN_KEY_PRESENCE = 0.5  # a key must appear in >= this fraction of samples to be mapped

_MASK_RE = re.compile(r"<([^>]*)>")


def _safe_literal(text: str) -> str:
    """``text`` with any ``<``/``>`` stripped, so it is safe to splice into a template."""
    return text.replace("<", "").replace(">", "")


_KEYED_ENGINES: dict[str, Any] = {
    "json": JsonEngine(),
    "kv": KvEngine(),
    "cef": CefEngine(),
    "leef": LeefEngine(),
}
_DELIMITED_FORMATS: dict[str, str] = {"csv": ",", "tsv": "\t"}

_PROTOCOL_NAMES: dict[int, str] = {
    1: "icmp",
    2: "igmp",
    6: "tcp",
    17: "udp",
    41: "ipv6",
    47: "gre",
    50: "esp",
    51: "ah",
    58: "ipv6-icmp",
    88: "eigrp",
    89: "ospf",
    103: "pim",
    112: "vrrp",
    115: "l2tp",
    132: "sctp",
}
_ACTION_ID_MAP = {
    "allow": 1,
    "allowed": 1,
    "accept": 1,
    "accepted": 1,
    "permit": 1,
    "permitted": 1,
    "pass": 1,
    "passed": 1,
    "deny": 2,
    "denied": 2,
    "drop": 2,
    "dropped": 2,
    "block": 2,
    "blocked": 2,
    "reject": 2,
    "rejected": 2,
}
_ACTION_NAME_MAP = {k: ("Allowed" if v == 1 else "Denied") for k, v in _ACTION_ID_MAP.items()}
_DISPOSITION_MAP = {k: ("Allowed" if v == 1 else "Blocked") for k, v in _ACTION_ID_MAP.items()}
_OUT_HINT_WORDS = ("src", "source", "sent", "out", "tx", "orig")
_IN_HINT_WORDS = ("dst", "dest", "destination", "rcv", "recv", "in", "rx", "resp")
_SEMANTIC_BASE_NAMES = {
    "source_ip": "src_ip",
    "destination_ip": "dst_ip",
    "ip_address": "ip",
    "port": "port",
    "protocol": "proto",
    "action": "action",
    "timestamp": "ts",
    "byte_count": "bytes",
    "interface_name": "intf",
    "unknown": "field",
}


class SuggestError(UlpfError):
    """``suggest_source_definition`` could not build a usable definition."""


# ======================================================================
# public entry point
# ======================================================================


def resolve_sample_lines(
    source_id: str,
    *,
    template_id: str | int | None = None,
    sample_lines: list[str] | None = None,
    settings: Settings | None = None,
    template_store: TemplateStore | None = None,
) -> list[str]:
    """Resolve the raw lines a caller wants — either given directly, or looked
    up from ``template_store`` by ``template_id``.

    Used by :func:`suggest_source_definition` itself, and by
    ``ulpf suggest-parser``/the API to get the *same* lines back for
    :func:`~ulpf.parse.templates.score.score_suggestion` without generating
    twice or duplicating the lookup.

    Raises:
        ValueError: Neither or both of ``template_id``/``sample_lines`` given.
        SuggestError: ``template_id`` given but not found for ``source_id``.
    """
    if (template_id is None) == (sample_lines is None):
        raise ValueError("pass exactly one of template_id or sample_lines")
    if template_id is not None:
        store = template_store or TemplateStore(settings or get_settings())
        return _lookup_sample_lines(store, source_id, template_id)
    return [line for line in (sample_lines or []) if line and line.strip()]


def suggest_source_definition(
    source_id: str,
    *,
    template_id: str | int | None = None,
    sample_lines: list[str] | None = None,
    settings: Settings | None = None,
    template_store: TemplateStore | None = None,
    name: str | None = None,
    vendor: str | None = None,
    product: str | None = None,
    min_samples: int = _MIN_SAMPLES,
) -> str:
    """Draft a complete source-definition YAML from sample raw lines.

    Args:
        source_id: The device/listener the samples came from (used for the
            template lookup and as a default vendor/product/name hint).
        template_id: Look up this template's stored samples via ``template_store``.
            Exactly one of ``template_id`` / ``sample_lines`` must be given.
        sample_lines: Raw lines to analyze directly (bypasses the store's
            5-sample cap — this is what ``ulpf suggest-parser --file`` uses).
        settings: Only consulted when ``template_id`` is given (to build the
            default ``template_store``).
        template_store: Override for tests.
        name/vendor/product: Override the derived source name / metadata.
        min_samples: Refuse to guess from fewer than this many usable lines.

    Returns:
        A complete YAML document, already validated against
        :class:`~ulpf.parse.dsl.schema.SourceDefinition`.

    Raises:
        ValueError: Neither or both of ``template_id``/``sample_lines`` given.
        SuggestError: Too few usable samples, or (should never happen) the
            generated document failed schema validation.
    """
    lines = resolve_sample_lines(
        source_id,
        template_id=template_id,
        sample_lines=sample_lines,
        settings=settings,
        template_store=template_store,
    )

    if len(lines) < min_samples:
        raise SuggestError(f"need at least {min_samples} sample lines, got {len(lines)}")

    outer, inner = _majority_format(lines)
    if inner in _KEYED_ENGINES:
        spec = _keyed_definition(inner, lines, outer)
    elif inner in _DELIMITED_FORMATS:
        spec = _delimited_definition(inner, lines, outer, _DELIMITED_FORMATS[inner])
    else:
        spec = _unstructured_definition(lines, outer)

    slug = _slugify(name or source_id)
    doc, review = _build_doc(slug, vendor, product, spec)
    header = _header_comment(source_id, template_id, len(lines), spec)

    body = yaml.safe_dump(doc, sort_keys=False, default_flow_style=False, allow_unicode=True)
    body = _annotate_review_lines(body, review)
    final_text = header + body

    _validate_or_raise(final_text)
    return final_text


# ======================================================================
# intermediate representation
# ======================================================================


@dataclass
class _PField:
    """One field this definition's parser will extract, plus its inferred meaning."""

    name: str
    guess: FieldGuess
    hint_text: str = ""


@dataclass
class _BuiltSpec:
    """Everything :func:`_build_doc` needs, independent of which format built it."""

    parse: dict[str, Any]
    pfields: list[_PField]
    detect: dict[str, Any]
    kind: str
    samples_used: int


# ======================================================================
# format sniffing
# ======================================================================


def _majority_format(lines: list[str]) -> tuple[str, str]:
    """The ``(outer, inner)`` format most of ``lines`` sniff as."""
    votes = Counter(sniff_layered(line) for line in lines)
    (outer, inner), _count = votes.most_common(1)[0]
    return outer, inner


def _strip_envelope(line: str) -> str:
    """The message body, with any syslog envelope removed (mirrors ``NormalizeStage``)."""
    _envelope, message = parse_syslog_envelope(line.encode("utf-8", "replace"))
    return message.decode("utf-8", "replace")


def _bodies(lines: list[str], outer: str) -> list[str]:
    return [_strip_envelope(line) if outer == "syslog" else line for line in lines]


# ======================================================================
# structured: json / kv / cef / leef
# ======================================================================


def _keyed_definition(engine_name: str, lines: list[str], outer: str) -> _BuiltSpec:
    """High-confidence path: the real engine already knows the field boundaries."""
    engine = _KEYED_ENGINES[engine_name]
    rows: list[dict[str, str]] = []
    for body in _bodies(lines, outer):
        try:
            parsed = engine.parse(body, {})
        except ParseError:
            continue
        rows.append({k: _stringify(v) for k, v in parsed.items()})
    if not rows:
        raise SuggestError(f"no sample line could be parsed as {engine_name}")

    keys = _ordered_key_union(rows, _MIN_KEY_PRESENCE)
    if not keys:
        raise SuggestError(f"no {engine_name} key appeared consistently across samples")
    sample_values = [[row.get(key, "") for key in keys] for row in rows]
    # embed each observed key as literal text ahead of its own wildcard, so
    # infer_field_types' keyword-based rules (interface/intf/port) see the
    # real field name, not a bare positional placeholder
    synthetic_template = " ".join(f"{_safe_literal(key)} <{i}>" for i, key in enumerate(keys))
    guesses = infer_field_types(synthetic_template, sample_values)
    pfields = [
        _PField(name=key, guess=guess, hint_text=key)
        for key, guess in zip(keys, guesses, strict=False)
    ]

    parse_block = {
        "envelope": "syslog" if outer == "syslog" else "none",
        "engine": engine_name,
        "options": {},
    }
    detect = _keyed_detect(lines, rows, keys)
    return _BuiltSpec(parse_block, pfields, detect, f"structured:{engine_name}", len(rows))


def _stringify(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def _ordered_key_union(rows: list[dict[str, str]], min_presence: float) -> list[str]:
    """Keys present in >= ``min_presence`` of ``rows``, in first-seen order."""
    order: list[str] = []
    counts: Counter[str] = Counter()
    for row in rows:
        for key in row:
            if key not in counts:
                order.append(key)
            counts[key] += 1
    threshold = min_presence * len(rows)
    return [key for key in order if counts[key] >= threshold]


def _keyed_detect(lines: list[str], rows: list[dict[str, str]], keys: list[str]) -> dict[str, Any]:
    """Prefer a constant ``key=value`` (or JSON ``"key"``) pair over a bare key."""
    candidates: list[str] = []
    for key in keys:
        values = {row.get(key) for row in rows if key in row}
        if len(values) == 1:
            (value,) = values
            if value and len(value) <= 40 and "\n" not in value:
                candidates.append(f'"{key}": "{value}"')  # json-shaped
                candidates.append(f"{key}={value}")  # kv/cef/leef-shaped
        candidates.append(f'"{key}"')  # bare key, json
        candidates.append(f"{key}=")  # bare key, kv/cef/leef
    return _build_detect_rule(_distinctive_literals(lines, candidates))


# ======================================================================
# delimited: csv / tsv
# ======================================================================


def _delimited_definition(fmt: str, lines: list[str], outer: str, delimiter: str) -> _BuiltSpec:
    bodies = _bodies(lines, outer)
    parsed_rows = [next(csv.reader(io.StringIO(body), delimiter=delimiter)) for body in bodies]
    width = Counter(len(row) for row in parsed_rows).most_common(1)[0][0]
    rows = [row for row in parsed_rows if len(row) == width]
    if not rows or width == 0:
        raise SuggestError(f"no consistent {fmt} column width found across samples")

    template = delimiter.join(f"<{i}>" for i in range(width))
    guesses = infer_field_types(template, rows)
    pfields = _name_generic_positions(guesses)

    parse_block = {
        "envelope": "syslog" if outer == "syslog" else "none",
        "engine": "csv",
        "options": {"delimiter": delimiter, "columns": [pf.name for pf in pfields]},
    }
    matching_lines = [
        line for line, row in zip(lines, parsed_rows, strict=False) if len(row) == width
    ]
    detect = _delimited_detect(matching_lines, rows, width, delimiter)
    return _BuiltSpec(parse_block, pfields, detect, f"delimited:{fmt}", len(rows))


def _delimited_detect(
    lines: list[str], rows: list[list[str]], width: int, delimiter: str
) -> dict[str, Any]:
    candidates: list[str] = []
    for col in range(width):
        values = {row[col] for row in rows}
        if len(values) == 1:
            (value,) = values
            if value and len(value) <= 40:
                candidates.append(value)
    literal_rules = _distinctive_literals(lines, candidates, max_n=1)
    field_count_rule = {"field_count": {"delimiter": delimiter, "equals": width}}
    if literal_rules:
        return {"all": [{"contains": literal_rules[0]}, field_count_rule]}
    return field_count_rule


# ======================================================================
# unstructured: dissect (preferred) / grok (fallback)
# ======================================================================


def _unstructured_definition(lines: list[str], outer: str) -> _BuiltSpec:
    bodies = _bodies(lines, outer)
    engine = _Drain3Engine(persistence_handler=None, config=load_drain3_config())
    mined = [engine.add_log_message(body)["template_mined"] for body in bodies]

    dominant = Counter(mined).most_common(1)[0][0]
    kept = [
        (body, line)
        for body, line, tmpl in zip(bodies, lines, mined, strict=False)
        if tmpl == dominant
    ]
    if len(kept) < _MIN_SAMPLES:
        raise SuggestError(
            "samples did not converge on one dominant shape; supply more/cleaner samples"
        )
    kept_bodies, kept_lines = zip(*kept, strict=False)
    param_lists = [engine.get_parameter_list(dominant, body) for body in kept_bodies]

    marks = list(_MASK_RE.finditer(dominant))
    guesses = infer_field_types(dominant, list(param_lists))
    pfields: list[_PField] = []
    used: set[str] = set()
    for i, (mark, guess) in enumerate(zip(marks, guesses, strict=False)):
        hint = dominant[marks[i - 1].end() if i > 0 else 0 : mark.start()]
        pfields.append(_PField(name=_unique_name(guess, i, used), guess=guess, hint_text=hint))

    if _dissect_safe(dominant, marks):
        pattern = _dissect_pattern(dominant, marks, pfields)
        engine_name, options = "dissect", {"pattern": pattern}
    else:
        pattern = _grok_pattern(dominant, marks, pfields)
        engine_name, options = "grok", {"pattern": pattern}

    parse_block = {
        "envelope": "syslog" if outer == "syslog" else "none",
        "engine": engine_name,
        "options": options,
    }
    detect = _unstructured_detect(list(kept_lines), dominant)
    return _BuiltSpec(parse_block, pfields, detect, "unstructured", len(kept_lines))


def _dissect_safe(template: str, marks: list[re.Match[str]]) -> bool:
    """Dissect needs a non-empty delimiter between every pair of adjacent placeholders."""
    return all(template[marks[i].end() : marks[i + 1].start()] for i in range(len(marks) - 1))


def _dissect_pattern(template: str, marks: list[re.Match[str]], pfields: list[_PField]) -> str:
    parts: list[str] = []
    cursor = 0
    for mark, pf in zip(marks, pfields, strict=False):
        parts.append(template[cursor : mark.start()])
        parts.append(f"%{{{pf.name}}}")
        cursor = mark.end()
    parts.append(template[cursor:])
    return "".join(parts)


_GROK_TYPE_FOR_MASK = {
    "IP": "IP",
    "PORT": "POSINT",
    "NUM": "NUMBER",
    "HEX": "BASE16NUM",
    "UUID": "UUID",
    "MAC": "NOTSPACE",
    "TIMESTAMP": "DATA",
    "QUOTED": "QUOTEDSTRING",
    "BYTES": "DATA",
    "*": "DATA",
}


def _grok_pattern(template: str, marks: list[re.Match[str]], pfields: list[_PField]) -> str:
    parts: list[str] = []
    cursor = 0
    for mark, pf in zip(marks, pfields, strict=False):
        parts.append(re.escape(template[cursor : mark.start()]))
        grok_type = _GROK_TYPE_FOR_MASK.get(mark.group(1).upper(), "DATA")
        parts.append(f"%{{{grok_type}:{pf.name}}}")
        cursor = mark.end()
    parts.append(re.escape(template[cursor:]))
    return "".join(parts)


def _unstructured_detect(lines: list[str], template: str) -> dict[str, Any]:
    literals = [seg.strip() for seg in _MASK_RE.split(template)]
    candidates = [seg for seg in literals if len(seg.strip()) >= 3]
    return _build_detect_rule(_distinctive_literals(lines, candidates))


def _name_generic_positions(guesses: list[FieldGuess]) -> list[_PField]:
    used: set[str] = set()
    return [_PField(name=_unique_name(g, i, used), guess=g) for i, g in enumerate(guesses)]


def _unique_name(guess: FieldGuess, position: int, used: set[str]) -> str:
    semantic = guess["inferred_semantic"]
    base = _SEMANTIC_BASE_NAMES.get(semantic, "field")
    if semantic in ("unknown", "ip_address"):
        base = f"{base}_{position}"
    name, n = base, 2
    while name in used:
        name = f"{base}_{n}"
        n += 1
    used.add(name)
    return name


# ======================================================================
# detect-rule construction (shared)
# ======================================================================


def _distinctive_literals(lines: list[str], candidates: list[str], max_n: int = 2) -> list[str]:
    """Candidates present verbatim in every line, longest (most specific) first."""
    present = sorted(
        {c for c in candidates if c and all(c in line for line in lines)}, key=len, reverse=True
    )
    picked: list[str] = []
    for candidate in present:
        if any(candidate in p or p in candidate for p in picked):
            continue
        picked.append(candidate)
        if len(picked) >= max_n:
            break
    return picked


def _build_detect_rule(literals: list[str]) -> dict[str, Any]:
    if not literals:
        return {"regex": r".+"}  # last resort: never emit an invalid (empty) detect rule
    if len(literals) == 1:
        return {"contains": literals[0]}
    return {"all": [{"contains": literal} for literal in literals]}


# ======================================================================
# semantic -> OCSF mapping
# ======================================================================


def _direction_hint(text: str) -> str | None:
    lowered = text.lower()
    if any(word in lowered for word in _OUT_HINT_WORDS):
        return "out"
    if any(word in lowered for word in _IN_HINT_WORDS):
        return "in"
    return None


def _nearest_ip_role(index: int, ip_positions: list[tuple[int, str]]) -> str | None:
    if not ip_positions:
        return None
    _pos, role = min(ip_positions, key=lambda item: abs(item[0] - index))
    return role


def _assign_ocsf(pfields: list[_PField]) -> tuple[dict[str, dict[str, Any]], dict[str, float]]:
    """Map each field's inferred semantic to an OCSF path (or leave it unmapped)."""
    fields: dict[str, dict[str, Any]] = {}
    review: dict[str, float] = {}
    taken = {
        "src_port": False,
        "dst_port": False,
        "bytes_out": False,
        "bytes_in": False,
        "src_intf": False,
        "dst_intf": False,
        "time": False,
    }

    def add(path: str, mapping: dict[str, Any], guess: FieldGuess) -> None:
        fields[path] = mapping
        if guess["confidence"] < REVIEW_THRESHOLD:
            review[path] = guess["confidence"]

    ip_positions: list[tuple[int, str]] = []
    for i, pf in enumerate(pfields):
        semantic = pf.guess["inferred_semantic"]
        if semantic == "source_ip":
            add("src_endpoint.ip", {"from": pf.name, "type": "ip", "required": True}, pf.guess)
            ip_positions.append((i, "src"))
        elif semantic == "destination_ip":
            add("dst_endpoint.ip", {"from": pf.name, "type": "ip", "required": True}, pf.guess)
            ip_positions.append((i, "dst"))

    for i, pf in enumerate(pfields):
        semantic = pf.guess["inferred_semantic"]
        if semantic in ("source_ip", "destination_ip", "ip_address", "unknown"):
            continue  # ip_address/unknown: intentionally left to `unmapped: keep_all`
        if semantic == "timestamp":
            _assign_timestamp(pf, taken, add)
        elif semantic == "protocol":
            _assign_protocol(pf, add)
        elif semantic == "action":
            _assign_action(pf, add)
        elif semantic == "port":
            _assign_slotted(
                pf,
                taken,
                add,
                "src_port",
                "dst_port",
                "src_endpoint.port",
                "dst_endpoint.port",
                "int",
                _nearest_ip_role(i, ip_positions),
            )
        elif semantic == "byte_count":
            _assign_slotted(
                pf,
                taken,
                add,
                "bytes_out",
                "bytes_in",
                "traffic.bytes_out",
                "traffic.bytes_in",
                "int",
                _direction_hint(pf.hint_text),
            )
        elif semantic == "interface_name":
            _assign_slotted(
                pf,
                taken,
                add,
                "src_intf",
                "dst_intf",
                "src_endpoint.interface_name",
                "dst_endpoint.interface_name",
                "str",
                _direction_hint(pf.hint_text),
            )
    return fields, review


def _assign_timestamp(pf: _PField, taken: dict[str, bool], add: Any) -> None:
    if taken["time"]:
        return
    add("time", {"from": pf.name, "type": "timestamp", "required": True}, pf.guess)
    taken["time"] = True


def _assign_protocol(pf: _PField, add: Any) -> None:
    add("connection_info.protocol_num", {"from": pf.name, "type": "int"}, pf.guess)
    add(
        "connection_info.protocol_name",
        {"from": pf.name, "map": {str(k): v for k, v in _PROTOCOL_NAMES.items()}, "default": None},
        pf.guess,
    )


def _assign_action(pf: _PField, add: Any) -> None:
    add("action_id", {"from": pf.name, "map": dict(_ACTION_ID_MAP), "default": 0}, pf.guess)
    add("action", {"from": pf.name, "map": dict(_ACTION_NAME_MAP), "default": None}, pf.guess)
    add("disposition", {"from": pf.name, "map": dict(_DISPOSITION_MAP), "default": None}, pf.guess)


def _assign_slotted(
    pf: _PField,
    taken: dict[str, bool],
    add: Any,
    out_slot: str,
    in_slot: str,
    out_path: str,
    in_path: str,
    field_type: str,
    hint: str | None,
) -> None:
    """Assign to the "out" (src/sent) or "in" (dst/rcvd) OCSF slot, by hint then by availability."""
    path: str | None = None
    if hint == "out" and not taken[out_slot]:
        path, slot = out_path, out_slot
    elif hint == "in" and not taken[in_slot]:
        path, slot = in_path, in_slot
    elif not taken[out_slot]:
        path, slot = out_path, out_slot
    elif not taken[in_slot]:
        path, slot = in_path, in_slot
    else:
        return  # both slots full: stays unmapped -> unmapped: keep_all
    taken[slot] = True
    add(path, {"from": pf.name, "type": field_type}, pf.guess)


# ======================================================================
# assembling the document
# ======================================================================


def _slugify(text: str) -> str:
    slug = re.sub(r"[^a-z0-9_-]+", "_", text.lower()).strip("_-")
    return slug if slug and slug[0].isalnum() else f"src_{slug}" if slug else "suggested_source"


def _build_doc(
    slug: str, vendor: str | None, product: str | None, spec: _BuiltSpec
) -> tuple[dict[str, Any], dict[str, float]]:
    fields, review = _assign_ocsf(spec.pfields)
    if "time" not in fields and spec.parse.get("envelope") == "syslog":
        # no field in the body itself looked like a timestamp, but the syslog
        # envelope always carries one - fall back to it (see iptables.yaml)
        fields["time"] = {"from": "envelope.timestamp", "type": "timestamp", "required": True}
    required = ["class_uid", "category_uid"]
    required.extend(
        path for path in ("src_endpoint.ip", "dst_endpoint.ip", "time") if path in fields
    )

    doc = {
        "name": slug,
        "version": "0.1.0-suggested",
        "vendor": vendor or "Unknown",
        "product": product or slug,
        "product_version": "unknown",
        "detect": spec.detect,
        "parse": spec.parse,
        "normalize": {
            "class_uid": 4001,
            "category_uid": 4,
            "activity_id": 6,
            "constants": {
                "metadata.product.vendor_name": vendor or "Unknown",
                "metadata.product.name": product or slug,
                "severity_id": 1,
            },
            "fields": fields,
            "unmapped": "keep_all",
        },
        "validate": {"required": required, "on_failure": "dead_letter"},
    }
    return doc, review


def _header_comment(
    source_id: str, template_id: str | int | None, n_samples: int, spec: _BuiltSpec
) -> str:
    template_note = template_id if template_id is not None else "n/a (built from raw sample lines)"
    lines = [
        "# Auto-generated by `ulpf suggest-parser` — REVIEW BEFORE DEPLOYING.",
        f"# source_id: {source_id}",
        f"# template_id: {template_note}",
        f"# generated from: {n_samples} sample line(s) ({spec.samples_used} used after sniffing)",
        f"# detection strategy: {spec.kind}",
        "#",
        "# per-field confidence:",
    ]
    for pf in spec.pfields:
        guess = pf.guess
        flag = "  <- REVIEW" if guess["confidence"] < REVIEW_THRESHOLD else ""
        lines.append(
            f"#   {pf.name}: {guess['inferred_semantic']} "
            f"(confidence {guess['confidence']:.2f}, mask={guess['mask_type']}){flag}"
        )
    lines.append("")
    return "\n".join(lines) + "\n"


def _annotate_review_lines(body: str, review: dict[str, float]) -> str:
    lines_out = body.splitlines()
    for path, confidence in review.items():
        pattern = re.compile(r"^(\s*)" + re.escape(path) + r":\s*$")
        for i, line in enumerate(lines_out):
            if pattern.match(line):
                lines_out[i] = f"{line}  # REVIEW REQUIRED (confidence {confidence:.2f})"
                break
    return "\n".join(lines_out) + "\n"


def _lookup_sample_lines(store: TemplateStore, source_id: str, template_id: str | int) -> list[str]:
    target = str(template_id)
    for row in store.list_templates(source_id=source_id):
        if row["template_id"] == target:
            return list(row["sample_lines"])
    raise SuggestError(f"no template {template_id!r} recorded for source_id {source_id!r}")


def _validate_or_raise(yaml_text: str) -> None:
    """Never return YAML that would fail to load — validate before handing it back."""
    try:
        parsed = yaml.safe_load(yaml_text)
        load_source_definition(parsed)
    except (_PydanticValidationError, yaml.YAMLError) as exc:
        raise SuggestError(f"generated definition failed validation: {exc}") from exc
